"use client";

import { FormEvent, useMemo, useState, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import {
  BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2, ChevronDown, Circle,
  CircleHelp, Download, FileCheck2, FileText, GraduationCap, LayoutDashboard,
  LogOut, Menu, MessageCirclePlus, MessageSquareText, Send, Settings,
  UploadCloud, UserRound, UserRoundCheck, X,
} from "lucide-react";
import { authClient } from "@/lib/auth/client";
import type {
  DashboardAppointment, DashboardBookingSlot, DashboardConsultation, DashboardDocument,
  DashboardLogbook, DashboardNotification, DashboardProgress, DashboardStudent, DashboardTitle,
} from "@/components/dashboard-types";

type Props={viewerName:string;period:string;student:DashboardStudent;consultations:DashboardConsultation[];documents:DashboardDocument[];appointments:DashboardAppointment[];titles:DashboardTitle[];logbook:DashboardLogbook[];progress:DashboardProgress[];notifications:DashboardNotification[];bookingSlots:DashboardBookingSlot[]};
const nav=[["Beranda Saya",LayoutDashboard],["Pengajuan Judul",FileCheck2],["Konsultasi",MessageSquareText],["Dokumen Skripsi",FileText],["Progress Tracker",BarChart3],["Jadwal & Booking",CalendarDays],["Catatan Bimbingan",BookOpen],["Notifikasi",Bell],["Profil Saya",UserRound]] as const;
const formatDate=(value:string)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
const formatDay=(value:string)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"long"}).format(new Date(value));
const formatSize=(bytes:number)=>bytes<1024*1024?`${Math.ceil(bytes/1024)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;
const statusLabel=(status:string)=>({ACTIVE:"Aktif",SUBMITTED:"Menunggu balasan",IN_REVIEW:"Sedang ditinjau",REVISION:"Perlu revisi",APPROVED:"Disetujui",REJECTED:"Ditolak",DONE:"Selesai",PENDING:"Menunggu",CONFIRMED:"Terkonfirmasi",COMPLETED:"Selesai",NOT_STARTED:"Belum dimulai",IN_PROGRESS:"Sedang berjalan"} as Record<string,string>)[status]||status;
const eligibilityLabel=(value:string)=>value==="ELIGIBLE"?"Layak":value==="NOT_YET"?"Belum layak":"Belum dinilai";

export default function StudentDashboard(props:Props){
  const {viewerName,period,student,consultations,documents,appointments,titles,logbook,progress,notifications,bookingSlots}=props;
  const router=useRouter(); const [active,setActive]=useState("Beranda Saya"); const [mobile,setMobile]=useState(false); const [busy,setBusy]=useState(""); const [toast,setToast]=useState("");
  const [subject,setSubject]=useState(""); const [message,setMessage]=useState(""); const [reply,setReply]=useState<Record<string,string>>({}); const [category,setCategory]=useState("NASKAH LENGKAP");
  const [titleForm,setTitleForm]=useState({title:"",background:"",researchProblem:"",objective:"",proposedMethod:"",initialReferences:""});
  const [logForm,setLogForm]=useState({entryDate:new Date().toISOString().slice(0,10),topic:"",summary:"",feedbackReceived:"",actionItems:"",nextMeetingTarget:"",meetingType:"CHAT"});
  const [bookingTopic,setBookingTopic]=useState<Record<string,string>>({});
  const unread=notifications.filter(item=>!item.readAt).length; const initials=viewerName.split(" ").map(x=>x[0]).join("").slice(0,2).toUpperCase();
  const upcoming=useMemo(()=>[...appointments].filter(a=>new Date(a.startsAt)>new Date()).slice(0,5),[appointments]);
  async function logout(){await authClient.signOut();router.replace("/");router.refresh()}
  async function requestJson(url:string,method:string,body:unknown,busyKey:string,success:string){setBusy(busyKey);const response=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json().catch(()=>({}));setBusy("");if(!response.ok){setToast(result.error||"Permintaan belum dapat diproses.");return false}setToast(success);router.refresh();return true}
  async function openConsultation(event:FormEvent){event.preventDefault();if(await requestJson("/api/consultations","POST",{subject,message},"consultation","Konsultasi berhasil dikirim.")){setSubject("");setMessage("")}}
  async function sendReply(event:FormEvent,id:string){event.preventDefault();const text=reply[id]?.trim();if(!text)return;if(await requestJson(`/api/consultations/${id}/messages`,"POST",{message:text},id,"Balasan berhasil dikirim."))setReply(v=>({...v,[id]:""}))}
  async function uploadDocument(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=form.elements.namedItem("file") as HTMLInputElement;if(!input.files?.[0])return setToast("Pilih berkas Word terlebih dahulu.");const data=new FormData();data.set("file",input.files[0]);data.set("category",category);setBusy("upload");const response=await fetch("/api/documents",{method:"POST",body:data});const result=await response.json().catch(()=>({}));setBusy("");if(!response.ok)return setToast(result.error||"Dokumen gagal diunggah.");form.reset();setCategory("NASKAH LENGKAP");setToast("Dokumen Word berhasil disimpan.");router.refresh()}
  async function submitTitle(event:FormEvent){event.preventDefault();if(await requestJson("/api/titles","POST",titleForm,"title","Pengajuan judul berhasil dikirim."))setTitleForm({title:"",background:"",researchProblem:"",objective:"",proposedMethod:"",initialReferences:""})}
  async function submitLogbook(event:FormEvent){event.preventDefault();const body={...logForm,actionItems:logForm.actionItems.split("\n").map(x=>x.trim()).filter(Boolean)};if(await requestJson("/api/logbook","POST",body,"logbook","Catatan bimbingan berhasil disimpan."))setLogForm(v=>({...v,topic:"",summary:"",feedbackReceived:"",actionItems:"",nextMeetingTarget:""}))}
  async function book(slot:DashboardBookingSlot){const topic=bookingTopic[slot.id]?.trim();if(!topic)return setToast("Isi topik bimbingan terlebih dahulu.");if(await requestJson("/api/bookings","POST",{action:"BOOK",slotId:slot.id,topic},`book-${slot.id}`,"Slot bimbingan berhasil dipesan."))setBookingTopic(v=>({...v,[slot.id]:""}))}
  async function markNotifications(all:boolean,id?:string){await requestJson("/api/notifications","PATCH",all?{all:true}:{id},"notification","Notifikasi ditandai sudah dibaca.")}
  function choose(label:string){setActive(label);setMobile(false)}

  return <div className="app-shell student-shell">
    <aside className={mobile?"sidebar open":"sidebar"}><div className="side-brand"><span><GraduationCap/></span><div>Bimbingan <b>Andaz</b><small>RUANG MAHASISWA</small></div><button aria-label="Tutup menu" onClick={()=>setMobile(false)}><X/></button></div>
      <nav>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>choose(label)}><Icon/>{label}{label==="Notifikasi"&&unread>0&&<em>{unread}</em>}</button>)}</nav>
      <div className="student-safety"><UserRoundCheck/><b>Akun mahasiswa aktif</b><small>Data Anda terpisah dan hanya terlihat oleh pengelola.</small></div>
      <div className="side-bottom"><button onClick={()=>choose("Pusat Bantuan")}><CircleHelp/> Pusat Bantuan</button><button onClick={()=>choose("Pengaturan")}><Settings/> Pengaturan</button><button onClick={logout}><LogOut/> Keluar</button><div className="profile-mini"><span>{initials}</span><p><b>{viewerName}</b><small>Mahasiswa · {student.nim}</small></p><ChevronDown/></div></div>
    </aside>{mobile&&<button className="scrim" aria-label="Tutup menu" onClick={()=>setMobile(false)}/>}<main className="dashboard-main"><header className="topbar"><button className="mobile-menu" aria-label="Buka menu" onClick={()=>setMobile(true)}><Menu/></button><div className="student-page-label"><GraduationCap/><span>Portal Mahasiswa</span></div><button className="term">{period}<ChevronDown/></button><button className="bell" onClick={()=>choose("Notifikasi")} aria-label={`${unread} notifikasi belum dibaca`}><Bell/>{unread>0&&<em>{unread}</em>}</button></header>
      <div className="content"><div className="student-welcome"><div><span>RUANG KERJA PRIBADI</span><h1>{active}</h1><p>Halo, {viewerName}. Pantau progres dan kirim pekerjaan Anda dari sini.</p></div><button className="button primary" onClick={()=>choose("Konsultasi")}><MessageCirclePlus/> Buka konsultasi</button></div>

      {active==="Beranda Saya"&&<><section className="student-hero panel"><div><small>PROGRES SKRIPSI</small><h2>{student.stage}</h2><p>{student.progress}% perjalanan akademik telah tercatat.</p><div><i style={{width:`${student.progress}%`}}/></div></div><aside><b>{student.program}</b><span>Program studi</span><b>{documents.length}</b><span>Dokumen tersimpan</span><b>{consultations.length}</b><span>Konsultasi</span><b>{eligibilityLabel(student.proposalEligibility)}</b><span>Kelayakan proposal</span><b>{eligibilityLabel(student.resultEligibility)}</b><span>Kelayakan hasil</span></aside></section><section className="student-actions"><button onClick={()=>choose("Pengajuan Judul")}><FileCheck2/><span><b>Ajukan judul</b><small>Kirim usulan penelitian</small></span></button><button onClick={()=>choose("Dokumen Skripsi")}><UploadCloud/><span><b>Unggah dokumen</b><small>Kirim berkas Word terbaru</small></span></button><button onClick={()=>choose("Konsultasi")}><MessageSquareText/><span><b>Tanya pembimbing</b><small>Buka atau balas konsultasi</small></span></button></section>{upcoming.length>0&&<section className="panel module-panel"><header><div><h2>Deadline dan agenda terdekat</h2><p>{upcoming.length} agenda mendatang</p></div></header><div className="record-list">{upcoming.map(a=><div className="static-record" key={a.id}><CalendarDays/><span><b>{a.topic}</b><small>{formatDate(a.startsAt)} · {a.method}</small></span></div>)}</div></section>}</>}

      {active==="Pengajuan Judul"&&<><section className="panel upload-panel"><header><div><h2>Ajukan judul skripsi</h2><p>Lengkapi pokok penelitian. Maksimal tiga pengajuan sepanjang proses.</p></div></header><form onSubmit={submitTitle}><label>Judul utama<input value={titleForm.title} onChange={e=>setTitleForm(v=>({...v,title:e.target.value}))} minLength={20} maxLength={500} required/></label><label>Latar belakang<textarea value={titleForm.background} onChange={e=>setTitleForm(v=>({...v,background:e.target.value}))} minLength={100} maxLength={10000} required/></label><label>Rumusan masalah<textarea value={titleForm.researchProblem} onChange={e=>setTitleForm(v=>({...v,researchProblem:e.target.value}))} minLength={20} required/></label><label>Tujuan penelitian<textarea value={titleForm.objective} onChange={e=>setTitleForm(v=>({...v,objective:e.target.value}))} minLength={20} required/></label><label>Metode yang diusulkan<input value={titleForm.proposedMethod} onChange={e=>setTitleForm(v=>({...v,proposedMethod:e.target.value}))}/></label><label>Referensi awal<textarea value={titleForm.initialReferences} onChange={e=>setTitleForm(v=>({...v,initialReferences:e.target.value}))} placeholder="Satu referensi per baris"/></label><button className="button primary" disabled={busy==="title"}><Send/>{busy==="title"?"Mengirim…":"Ajukan judul"}</button></form></section><RecordPanel title="Riwayat pengajuan" empty="Belum ada pengajuan judul.">{titles.map(item=><article className="detail-record" key={item.id}><div><b>Usulan {item.sequence}: {item.title}</b><small>{formatDate(item.createdAt)}</small><p>{item.decisionReason||"Belum ada catatan dosen."}</p></div><i className={`status ${item.decision==="APPROVED"?"green":item.decision==="REJECTED"?"red":"yellow"}`}>{statusLabel(item.decision)}</i></article>)}</RecordPanel></>}

      {active==="Konsultasi"&&<section className="module-grid student-conversations"><article className="panel consultation-compose"><header><div><h2>Buka konsultasi baru</h2><p>Jelaskan topik dan pertanyaan Anda secara ringkas.</p></div></header><form onSubmit={openConsultation}><label>Subjek<input value={subject} onChange={e=>setSubject(e.target.value)} minLength={3} maxLength={180} required/></label><label>Pesan<textarea value={message} onChange={e=>setMessage(e.target.value)} minLength={3} maxLength={5000} required/></label><button className="button primary" disabled={busy==="consultation"}><Send/>{busy==="consultation"?"Mengirim…":"Kirim konsultasi"}</button></form></article>{consultations.map(c=><article className="panel conversation" key={c.id}><header><div><h2>{c.subject}</h2><p>{statusLabel(c.status)}</p></div></header><div className="messages">{c.messages.map(m=><div className={m.senderRole==="STUDENT"?"mine":""} key={m.id}><b>{m.senderRole==="STUDENT"?"Saya":m.senderName}</b><p>{m.body}</p><small>{formatDate(m.createdAt)}</small></div>)}</div><form className="reply-form" onSubmit={e=>sendReply(e,c.id)}><input value={reply[c.id]||""} onChange={e=>setReply(v=>({...v,[c.id]:e.target.value}))} placeholder="Tulis balasan…"/><button aria-label="Kirim balasan" disabled={busy===c.id}><Send/></button></form></article>)}</section>}

      {active==="Dokumen Skripsi"&&<><section className="panel upload-panel"><header><div><h2>Unggah dokumen Word</h2><p>Format .doc atau .docx, maksimum 4 MB.</p></div></header><form onSubmit={uploadDocument}><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option>NASKAH LENGKAP</option><option>PROPOSAL</option><option>BAB I</option><option>BAB II</option><option>BAB III</option><option>BAB IV</option><option>BAB V</option></select></label><label className="file-drop"><UploadCloud/><span><b>Pilih berkas Word</b><small>.doc atau .docx · maksimal 4 MB</small></span><input name="file" type="file" accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" required/></label><button className="button primary" disabled={busy==="upload"}><UploadCloud/>{busy==="upload"?"Mengunggah…":"Unggah dokumen"}</button></form></section><RecordPanel title="Riwayat dokumen saya" empty="Belum ada dokumen.">{documents.map(d=><div className="static-record" key={d.id}><FileText/><span><b>{d.name}</b><small>{d.category} · Versi {d.version} · {formatSize(d.sizeBytes)} · {formatDate(d.createdAt)}</small></span><i className="status yellow">{statusLabel(d.status)}</i><a className="icon-action" href={`/api/documents/${d.id}/download`} aria-label={`Unduh ${d.name}`}><Download/></a></div>)}</RecordPanel></>}

      {active==="Progress Tracker"&&<><section className="student-hero panel"><div><small>PROGRES KESELURUHAN</small><h2>{student.progress}% selesai</h2><p>Tahap aktif: {student.stage}</p><div><i style={{width:`${student.progress}%`}}/></div></div></section><section className="panel timeline-list">{progress.map(item=><article key={item.id}><span className={item.status==="APPROVED"?"done":item.status==="IN_PROGRESS"?"current":""}>{item.status==="APPROVED"?<CheckCircle2/>:<Circle/>}</span><div><b>{item.name}</b><small>{statusLabel(item.status)} · Bobot {item.weight}%</small></div></article>)}</section></>}

      {active==="Jadwal & Booking"&&<><RecordPanel title="Slot bimbingan tersedia" empty="Belum ada slot bimbingan yang dibuka dosen.">{bookingSlots.filter(s=>new Date(s.startsAt)>new Date()).map(slot=><article className="booking-record" key={slot.id}><CalendarDays/><div><b>{slot.lecturerName}</b><small>{formatDate(slot.startsAt)}–{new Intl.DateTimeFormat("id-ID",{timeStyle:"short"}).format(new Date(slot.endsAt))} · {slot.method}</small><p>{slot.locationOrUrl||"Lokasi diinformasikan dosen"} · {slot.booked}/{slot.quota} terisi</p></div>{slot.myBookingId?<i className="status green">{statusLabel(slot.myBookingStatus||"CONFIRMED")}</i>:<div className="inline-book"><input aria-label="Topik booking" value={bookingTopic[slot.id]||""} onChange={e=>setBookingTopic(v=>({...v,[slot.id]:e.target.value}))} placeholder="Topik bimbingan"/><button className="button primary" disabled={busy===`book-${slot.id}`||slot.booked>=slot.quota} onClick={()=>book(slot)}>Pesan</button></div>}</article>)}</RecordPanel><RecordPanel title="Jadwal saya" empty="Belum ada jadwal bimbingan.">{appointments.map(a=><div className="static-record" key={a.id}><CalendarDays/><span><b>{a.topic}</b><small>{formatDate(a.startsAt)} · {a.method}</small></span><i className="status yellow">{statusLabel(a.decision)}</i></div>)}</RecordPanel></>}

      {active==="Catatan Bimbingan"&&<><section className="panel upload-panel"><header><div><h2>Catat sesi bimbingan</h2><p>Simpan topik, hasil diskusi, dan tindak lanjut.</p></div></header><form onSubmit={submitLogbook}><label>Tanggal<input type="date" value={logForm.entryDate} onChange={e=>setLogForm(v=>({...v,entryDate:e.target.value}))} required/></label><label>Topik<input value={logForm.topic} onChange={e=>setLogForm(v=>({...v,topic:e.target.value}))} minLength={3} required/></label><label>Ringkasan<textarea value={logForm.summary} onChange={e=>setLogForm(v=>({...v,summary:e.target.value}))} minLength={10} required/></label><label>Masukan dosen<textarea value={logForm.feedbackReceived} onChange={e=>setLogForm(v=>({...v,feedbackReceived:e.target.value}))}/></label><label>Tindak lanjut<textarea value={logForm.actionItems} onChange={e=>setLogForm(v=>({...v,actionItems:e.target.value}))} placeholder="Satu tindakan per baris"/></label><label>Target pertemuan berikutnya<input type="date" value={logForm.nextMeetingTarget} onChange={e=>setLogForm(v=>({...v,nextMeetingTarget:e.target.value}))}/></label><label>Jenis<select value={logForm.meetingType} onChange={e=>setLogForm(v=>({...v,meetingType:e.target.value}))}><option value="CHAT">Konsultasi chat</option><option value="IN_PERSON">Bimbingan langsung</option><option value="DOCUMENT_REVISION">Revisi dokumen</option></select></label><button className="button primary" disabled={busy==="logbook"}><BookOpen/>{busy==="logbook"?"Menyimpan…":"Simpan catatan"}</button></form></section><RecordPanel title={`${logbook.length} catatan bimbingan`} empty="Belum ada catatan bimbingan.">{logbook.map(item=><article className="detail-record" key={item.id}><div><b>{item.topic}</b><small>{formatDay(item.entryDate)} · {item.meetingType}</small><p>{item.summary}</p>{item.feedbackReceived&&<p><strong>Masukan dosen:</strong> {item.feedbackReceived}</p>}</div><i className={`status ${item.isVerified?"green":"yellow"}`}>{item.isVerified?"Terverifikasi":"Menunggu verifikasi"}</i></article>)}</RecordPanel></>}

      {active==="Notifikasi"&&<section className="panel module-panel"><header><div><h2>Pusat notifikasi</h2><p>{unread} belum dibaca</p></div>{unread>0&&<button className="button secondary" onClick={()=>markNotifications(true)}>Tandai semua dibaca</button>}</header><div className="record-list">{notifications.map(item=><button key={item.id} className={item.readAt?"":"unread-record"} onClick={()=>!item.readAt&&markNotifications(false,item.id)}><Bell/><span><b>{item.title}</b><small>{item.body} · {formatDate(item.createdAt)}</small></span>{!item.readAt&&<i className="status blue">Baru</i>}</button>)}{notifications.length===0&&<StudentEmpty text="Belum ada notifikasi."/>}</div></section>}

      {active==="Profil Saya"&&<Profile viewerName={viewerName} student={student}/>} {active==="Pusat Bantuan"&&<section className="panel help-panel"><header><div><h2>Panduan mahasiswa</h2><p>Langkah utama menggunakan Bimbingan Andaz.</p></div></header><div className="help-grid"><article><FileCheck2/><b>Ajukan judul</b><p>Lengkapi judul, latar belakang, rumusan masalah, tujuan, metode, dan referensi awal.</p></article><article><UploadCloud/><b>Unggah naskah</b><p>Pilih kategori dan unggah berkas Word maksimum 4 MB.</p></article><article><MessageSquareText/><b>Buka konsultasi</b><p>Kirim pertanyaan dan lanjutkan diskusi pada percakapan yang sama.</p></article><article><BookOpen/><b>Isi catatan</b><p>Catat setiap sesi dan tunggu verifikasi dosen.</p></article></div></section>} {active==="Pengaturan"&&<section className="panel profile-card"><header><div><h2>Pengaturan akun</h2><p>Login, kata sandi, dan sesi dikelola aman oleh Neon Auth.</p></div></header><dl><div><dt>Nama</dt><dd>{viewerName}</dd></div><div><dt>NIM</dt><dd>{student.nim}</dd></div><div><dt>Status</dt><dd><i className="status green">Aktif</i></dd></div></dl></section>}
      </div></main>{toast&&<div className="toast" role="status"><UserRoundCheck/><span>{toast}</span><button aria-label="Tutup pemberitahuan" onClick={()=>setToast("")}><X/></button></div>}
  </div>;
}

function RecordPanel({title,empty,children}:{title:string;empty:string;children:ReactNode}){const hasChildren=Array.isArray(children)?children.length>0:Boolean(children);return <section className="panel module-panel"><header><div><h2>{title}</h2></div></header><div className="record-list">{hasChildren?children:<StudentEmpty text={empty}/>}</div></section>}
function StudentEmpty({text}:{text:string}){return <div className="empty compact-empty"><span><GraduationCap/></span><h2>{text}</h2><p>Data akan muncul otomatis setelah fitur digunakan.</p></div>}
function Profile({viewerName,student}:{viewerName:string;student:DashboardStudent}){return <section className="panel profile-card"><header><div><h2>Identitas akademik</h2><p>Informasi akun yang telah disetujui pengelola.</p></div></header><dl><div><dt>Nama</dt><dd>{viewerName}</dd></div><div><dt>NIM</dt><dd>{student.nim}</dd></div><div><dt>Program</dt><dd>{student.program}</dd></div><div><dt>Status akun</dt><dd><i className="status green">Aktif</i></dd></div><div><dt>Tahap saat ini</dt><dd>{student.stage}</dd></div><div><dt>Kelayakan ujian proposal</dt><dd>{eligibilityLabel(student.proposalEligibility)}</dd></div><div><dt>Kelayakan ujian hasil</dt><dd>{eligibilityLabel(student.resultEligibility)}</dd></div><div><dt>Total konsultasi</dt><dd>{student.consultationCount} kali</dd></div></dl></section>}
