import { redirect } from "next/navigation";
import Dashboard from "@/components/dashboard";
import StudentDashboard from "@/components/student-dashboard";
import type {
  DashboardAppointment, DashboardAudit, DashboardBookingRequest, DashboardBookingSlot, DashboardCommentTemplate, DashboardConsultation,
  DashboardDocument, DashboardLogbook, DashboardMessage, DashboardNotification,
  DashboardPeriod, DashboardProgress, DashboardStage, DashboardStudent, DashboardSuratRequest, DashboardSuratTemplate, DashboardTitle,
} from "@/components/dashboard-types";
import { getSql } from "@/lib/db";
import { getViewer } from "@/lib/viewer";

export const dynamic = "force-dynamic";

export default async function DashboardPage() {
  const viewer = await getViewer();
  if (!viewer) redirect("/");
  if (viewer.role === "STUDENT" && viewer.status === "PENDING") redirect("/pending");
  if (viewer.status === "REJECTED" || viewer.status === "DISABLED") redirect("/pending");

  const sql = getSql();
  const canSeeAll = viewer.role === "ADMIN";
  const isStudent = viewer.role === "STUDENT";
  const canManage = viewer.role === "ADMIN" || viewer.role === "LECTURER";
  const [studentRows, periodNameRows, documentRows, consultationRows, appointmentRows, titleRows, logbookRows, progressRows, notificationRows, bookingRows, bookingRequestRows, stageRows, commentTemplateRows, suratTemplateRows, suratRequestRows, periodRows, auditRows] = await Promise.all([
    sql`SELECT p.id::text,rp.id::text AS project_id,p.full_name AS name,sp.nim,sp.program::text,sp.whatsapp,sp.cohort,sp.class_name,COALESCE(ps.name,'Belum mulai') AS stage,COALESCE(ps.weight,0)::float AS progress,p.status::text,GREATEST(p.updated_at,COALESCE(rp.updated_at,p.updated_at)) AS updated_at,rp.archived_at,(SELECT count(*)::int FROM public.guidance_threads gt WHERE gt.project_id=rp.id) AS consultation_count,COALESCE((SELECT array_agg(gt.subject ORDER BY gt.updated_at DESC) FROM public.guidance_threads gt WHERE gt.project_id=rp.id),ARRAY[]::text[]) AS consultation_topics,COALESCE((SELECT array_agg(lp.full_name ORDER BY lp.full_name) FROM public.supervision_assignments sa2 JOIN public.profiles lp ON lp.id=sa2.lecturer_id WHERE sa2.project_id=rp.id AND sa2.is_active),ARRAY[]::text[]) AS supervisors,COALESCE((SELECT e.decision FROM public.exam_eligibility_decisions e WHERE e.project_id=rp.id AND e.exam_type='PROPOSAL'),'NOT_ASSESSED') AS proposal_eligibility,COALESCE((SELECT e.decision FROM public.exam_eligibility_decisions e WHERE e.project_id=rp.id AND e.exam_type='RESULT'),'NOT_ASSESSED') AS result_eligibility FROM public.profiles p JOIN public.student_profiles sp ON sp.profile_id=p.id LEFT JOIN public.research_projects rp ON rp.student_id=p.id LEFT JOIN public.progress_stages ps ON ps.id=rp.current_stage_id WHERE p.role='STUDENT' AND (${canSeeAll} OR (${isStudent} AND p.id=${viewer.id}::uuid) OR EXISTS(SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active)) ORDER BY p.full_name`,
    sql`SELECT name FROM public.academic_periods WHERE is_active=true LIMIT 1`,
    sql`SELECT v.id::text,p.full_name AS student_name,d.category,v.original_name AS name,v.version_no,v.status::text,v.size_bytes::float,v.created_at,up.full_name AS uploader_name,up.role::text AS uploader_role FROM public.document_versions v JOIN public.profiles up ON up.id=v.uploaded_by JOIN public.documents d ON d.id=v.document_id JOIN public.research_projects rp ON rp.id=d.project_id JOIN public.profiles p ON p.id=rp.student_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS (SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) ORDER BY v.created_at DESC`,
    sql`SELECT gt.id::text,p.full_name AS student_name,gt.subject,gt.status::text,gt.updated_at,COALESCE(jsonb_agg(jsonb_build_object('id',m.id::text,'senderName',sender.full_name,'senderRole',sender.role::text,'body',m.body,'createdAt',m.created_at) ORDER BY m.created_at) FILTER(WHERE m.id IS NOT NULL),'[]'::jsonb) AS messages FROM public.guidance_threads gt JOIN public.research_projects rp ON rp.id=gt.project_id JOIN public.profiles p ON p.id=rp.student_id LEFT JOIN public.messages m ON m.thread_id=gt.id AND m.deleted_at IS NULL LEFT JOIN public.profiles sender ON sender.id=m.sender_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS (SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) GROUP BY gt.id,p.full_name ORDER BY gt.updated_at DESC`,
    sql`SELECT a.id::text,a.topic,p.full_name AS student_name,a.starts_at,a.method,a.decision::text,a.meeting_url FROM public.appointments a JOIN public.research_projects rp ON rp.id=a.project_id JOIN public.profiles p ON p.id=rp.student_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS (SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) ORDER BY a.starts_at`,
    sql`SELECT ts.id::text,p.id::text AS student_id,p.full_name AS student_name,ts.sequence_no,ts.title,ts.background,ts.research_problem,ts.objective,ts.proposed_method,ts.initial_references,ts.decision::text,ts.decision_reason,ts.created_at FROM public.title_submissions ts JOIN public.research_projects rp ON rp.id=ts.project_id JOIN public.profiles p ON p.id=rp.student_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS (SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) ORDER BY ts.created_at DESC`,
    sql`SELECT l.id::text,p.full_name AS student_name,l.entry_date,l.topic,l.summary,l.feedback_received,l.action_items,l.next_meeting_target,l.meeting_type,l.is_verified FROM public.logbook_entries l JOIN public.research_projects rp ON rp.id=l.project_id JOIN public.profiles p ON p.id=rp.student_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS (SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) ORDER BY l.entry_date DESC,l.created_at DESC`,
    isStudent ? sql`SELECT ps.id,ps.name,ps.weight::float,CASE WHEN ps.id<rp.current_stage_id THEN 'APPROVED' WHEN ps.id=rp.current_stage_id THEN 'IN_PROGRESS' ELSE 'NOT_STARTED' END AS status FROM public.progress_stages ps CROSS JOIN public.research_projects rp WHERE rp.student_id=${viewer.id}::uuid ORDER BY ps.id` : Promise.resolve([]),
    sql`SELECT id::text,title,body,type,target_url,read_at,created_at FROM public.notifications WHERE recipient_id=${viewer.id}::uuid ORDER BY created_at DESC LIMIT 100`,
    sql`SELECT s.id::text,p.full_name AS lecturer_name,s.starts_at,s.ends_at,s.method,s.location_or_url,s.quota,count(br.id) FILTER(WHERE br.status IN('PENDING','CONFIRMED'))::int AS booked,max(br.id::text) FILTER(WHERE rp.student_id=${viewer.id}::uuid) AS my_booking_id,max(br.status) FILTER(WHERE rp.student_id=${viewer.id}::uuid) AS my_booking_status FROM public.booking_slots s JOIN public.profiles p ON p.id=s.lecturer_id LEFT JOIN public.booking_requests br ON br.slot_id=s.id LEFT JOIN public.research_projects rp ON rp.id=br.project_id WHERE s.is_active AND (s.starts_at>now() OR ${canManage}) GROUP BY s.id,p.full_name ORDER BY s.starts_at`,
    canManage ? sql`SELECT br.id::text,p.full_name AS student_name,p.id::text AS student_id,br.topic,br.note,br.status::text,s.starts_at,s.ends_at,s.method,s.location_or_url,br.created_at FROM public.booking_requests br JOIN public.booking_slots s ON s.id=br.slot_id JOIN public.research_projects rp ON rp.id=br.project_id JOIN public.profiles p ON p.id=rp.student_id WHERE ${canSeeAll} OR s.lecturer_id=${viewer.id}::uuid ORDER BY s.starts_at DESC` : Promise.resolve([]),
    sql`SELECT id,name,weight::float FROM public.progress_stages ORDER BY id`,
    canManage ? sql`SELECT ct.id::text,ct.category,ct.title,ct.content,p.full_name AS owner_name,ct.updated_at FROM public.comment_templates ct JOIN public.profiles p ON p.id=ct.owner_id WHERE ${canSeeAll} OR ct.owner_id=${viewer.id}::uuid ORDER BY ct.category,ct.title` : Promise.resolve([]),
    sql`SELECT id::text,name,document_type,body_template,is_active FROM public.surat_templates WHERE is_active OR ${canManage} ORDER BY name`,
    sql`SELECT sr.id::text,p.full_name AS student_name,p.id::text AS student_id,st.name AS template_name,st.document_type,sr.purpose,sr.status::text,sr.reviewer_notes,sr.created_at,sr.reviewed_at FROM public.surat_requests sr JOIN public.research_projects rp ON rp.id=sr.project_id JOIN public.profiles p ON p.id=rp.student_id LEFT JOIN public.surat_templates st ON st.id=sr.template_id WHERE ${canSeeAll} OR (${isStudent} AND rp.student_id=${viewer.id}::uuid) OR EXISTS(SELECT 1 FROM public.supervision_assignments sa WHERE sa.project_id=rp.id AND sa.lecturer_id=${viewer.id}::uuid AND sa.is_active) ORDER BY sr.created_at DESC`,
    canSeeAll ? sql`SELECT id::text,name,semester,academic_year,starts_on,ends_on,is_active,is_locked FROM public.academic_periods ORDER BY starts_on DESC` : Promise.resolve([]),
    canSeeAll ? sql`SELECT a.id::text,COALESCE(p.full_name,'Sistem') AS actor_name,a.action,a.entity_type,a.entity_id,a.created_at FROM public.audit_logs a LEFT JOIN public.profiles p ON p.id=a.actor_id ORDER BY a.created_at DESC LIMIT 200` : Promise.resolve([]),
  ]);

  const students:DashboardStudent[]=studentRows.map(row=>({id:String(row.id),projectId:row.project_id?String(row.project_id):null,name:String(row.name),nim:String(row.nim),program:String(row.program),whatsapp:String(row.whatsapp||""),cohort:Number(row.cohort||0),className:String(row.class_name||""),supervisors:Array.isArray(row.supervisors)?row.supervisors.map(String):[],stage:String(row.stage),progress:Number(row.progress),status:String(row.status),updatedAt:new Date(row.updated_at as string).toISOString(),archivedAt:row.archived_at?new Date(row.archived_at as string).toISOString():null,consultationCount:Number(row.consultation_count||0),consultationTopics:Array.isArray(row.consultation_topics)?row.consultation_topics.map(String):[],proposalEligibility:String(row.proposal_eligibility||"NOT_ASSESSED"),resultEligibility:String(row.result_eligibility||"NOT_ASSESSED")}));
  const documents:DashboardDocument[]=documentRows.map(row=>({id:String(row.id),studentName:String(row.student_name),category:String(row.category),name:String(row.name),version:Number(row.version_no),status:String(row.status),sizeBytes:Number(row.size_bytes),createdAt:new Date(row.created_at as string).toISOString(),uploaderName:String(row.uploader_name||row.student_name),uploaderRole:String(row.uploader_role||"STUDENT")}));
  const consultations:DashboardConsultation[]=consultationRows.map(row=>({id:String(row.id),studentName:String(row.student_name),subject:String(row.subject),status:String(row.status),updatedAt:new Date(row.updated_at as string).toISOString(),messages:(row.messages as DashboardMessage[]).map(message=>({...message,createdAt:new Date(message.createdAt).toISOString()}))}));
  const appointments:DashboardAppointment[]=appointmentRows.map(row=>({id:String(row.id),topic:String(row.topic),studentName:String(row.student_name),startsAt:new Date(row.starts_at as string).toISOString(),method:String(row.method),decision:String(row.decision),meetingUrl:row.meeting_url?String(row.meeting_url):null}));
  const titles:DashboardTitle[]=titleRows.map(row=>({id:String(row.id),studentId:String(row.student_id),studentName:String(row.student_name),sequence:Number(row.sequence_no),title:String(row.title),background:String(row.background),researchProblem:String(row.research_problem),objective:String(row.objective),proposedMethod:row.proposed_method?String(row.proposed_method):null,initialReferences:row.initial_references?String(row.initial_references):null,decision:String(row.decision),decisionReason:row.decision_reason?String(row.decision_reason):null,createdAt:new Date(row.created_at as string).toISOString()}));
  const logbook:DashboardLogbook[]=logbookRows.map(row=>({id:String(row.id),studentName:String(row.student_name),entryDate:String(row.entry_date),topic:String(row.topic),summary:String(row.summary),feedbackReceived:row.feedback_received?String(row.feedback_received):null,actionItems:Array.isArray(row.action_items)?row.action_items.map(String):[],nextMeetingTarget:row.next_meeting_target?String(row.next_meeting_target):null,meetingType:String(row.meeting_type),isVerified:Boolean(row.is_verified)}));
  const progress:DashboardProgress[]=progressRows.map(row=>({id:Number(row.id),name:String(row.name),weight:Number(row.weight),status:String(row.status) as DashboardProgress["status"]}));
  const notifications:DashboardNotification[]=notificationRows.map(row=>({id:String(row.id),title:String(row.title),body:String(row.body),type:String(row.type),targetUrl:row.target_url?String(row.target_url):null,readAt:row.read_at?new Date(row.read_at as string).toISOString():null,createdAt:new Date(row.created_at as string).toISOString()}));
  const bookingSlots:DashboardBookingSlot[]=bookingRows.map(row=>({id:String(row.id),lecturerName:String(row.lecturer_name),startsAt:new Date(row.starts_at as string).toISOString(),endsAt:new Date(row.ends_at as string).toISOString(),method:String(row.method),locationOrUrl:row.location_or_url?String(row.location_or_url):null,quota:Number(row.quota),booked:Number(row.booked||0),myBookingId:row.my_booking_id?String(row.my_booking_id):null,myBookingStatus:row.my_booking_status?String(row.my_booking_status):null}));
  const bookingRequests:DashboardBookingRequest[]=bookingRequestRows.map(row=>({id:String(row.id),studentName:String(row.student_name),studentId:String(row.student_id),topic:String(row.topic),note:row.note?String(row.note):null,status:String(row.status),startsAt:new Date(row.starts_at as string).toISOString(),endsAt:new Date(row.ends_at as string).toISOString(),method:String(row.method),locationOrUrl:row.location_or_url?String(row.location_or_url):null,createdAt:new Date(row.created_at as string).toISOString()}));
  const stages:DashboardStage[]=stageRows.map(row=>({id:Number(row.id),name:String(row.name),weight:Number(row.weight)}));
  const commentTemplates:DashboardCommentTemplate[]=commentTemplateRows.map(row=>({id:String(row.id),category:String(row.category),title:String(row.title),content:String(row.content),ownerName:String(row.owner_name),updatedAt:new Date(row.updated_at as string).toISOString()}));
  const suratTemplates:DashboardSuratTemplate[]=suratTemplateRows.map(row=>({id:String(row.id),name:String(row.name),documentType:String(row.document_type),bodyTemplate:String(row.body_template),isActive:Boolean(row.is_active)}));
  const suratRequests:DashboardSuratRequest[]=suratRequestRows.map(row=>({id:String(row.id),studentName:String(row.student_name),studentId:String(row.student_id),templateName:row.template_name?String(row.template_name):null,documentType:row.document_type?String(row.document_type):null,purpose:String(row.purpose),status:String(row.status),reviewerNotes:row.reviewer_notes?String(row.reviewer_notes):null,createdAt:new Date(row.created_at as string).toISOString(),reviewedAt:row.reviewed_at?new Date(row.reviewed_at as string).toISOString():null}));
  const periods:DashboardPeriod[]=periodRows.map(row=>({id:String(row.id),name:String(row.name),semester:Number(row.semester),academicYear:row.academic_year?String(row.academic_year):null,startsOn:String(row.starts_on),endsOn:String(row.ends_on),isActive:Boolean(row.is_active),isLocked:Boolean(row.is_locked)}));
  const audits:DashboardAudit[]=auditRows.map(row=>({id:String(row.id),actorName:String(row.actor_name),action:String(row.action),entityType:String(row.entity_type),entityId:String(row.entity_id),createdAt:new Date(row.created_at as string).toISOString()}));
  const period=String((periodNameRows[0] as {name?:string}|undefined)?.name||"Periode belum diatur");

  if(viewer.role==="STUDENT"){
    const student=students[0]; if(!student) redirect("/register");
    return <StudentDashboard viewerName={viewer.fullName} period={period} currentTime={new Date().toISOString()} student={student} consultations={consultations} documents={documents} appointments={appointments} titles={titles} logbook={logbook} progress={progress} notifications={notifications} bookingSlots={bookingSlots} suratTemplates={suratTemplates} suratRequests={suratRequests}/>;
  }
  return <Dashboard viewerName={viewer.fullName} viewerRole={viewer.role} period={period} students={students} consultations={consultations} documents={documents} appointments={appointments} titles={titles} logbook={logbook} notifications={notifications} bookingSlots={bookingSlots} bookingRequests={bookingRequests} stages={stages} commentTemplates={commentTemplates} suratTemplates={suratTemplates} suratRequests={suratRequests} periods={periods} audits={audits} currentTime={new Date().toISOString()}/>;
}
